# Generated by Django 4.2.14 on 2024-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=-1, null=True)),
                ('catagory', models.CharField(blank=True, max_length=200, null=True)),
                ('googleMapsUri', models.CharField(blank=True, default='url not found', max_length=200, null=True)),
                ('businessStatus', models.CharField(blank=True, default='closed', max_length=200, null=True)),
                ('formattedAddress', models.TextField(blank=True, null=True)),
                ('locationLongitude', models.DecimalField(decimal_places=7, default=0, max_digits=9)),
                ('locationLatitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('userRatingCount', models.IntegerField(blank=True, default=-1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSONDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jsonData', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
