# Generated by Django 4.2.14 on 2024-08-14 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catagory', models.CharField(blank=True, default='other', max_length=200, null=True)),
                ('subCatagory', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSONDataModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jsonData', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummeryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('districtCode', models.IntegerField(blank=True, null=True)),
                ('subdistrictCode', models.IntegerField(blank=True, null=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategicbi.phasemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=-1, null=True)),
                ('googleMapsUri', models.CharField(blank=True, default='url not found', max_length=200, null=True)),
                ('businessStatus', models.CharField(blank=True, default='closed', max_length=200, null=True)),
                ('formattedAddress', models.TextField(blank=True, null=True)),
                ('locationLongitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('locationLatitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('userRatingCount', models.IntegerField(blank=True, default=-1, null=True)),
                ('stateCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('districtCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('subdistrictCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('villageCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategicbi.catagorymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stateCode', models.IntegerField(blank=True, null=True)),
                ('districtCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('subdistrictCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('villageCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategicbi.catagorymodel')),
            ],
            options={
                'indexes': [models.Index(fields=['stateCode', 'districtCode', 'catagory'], name='strategicbi_stateCo_6f885c_idx')],
            },
        ),
    ]
