# Generated by Django 4.2.14 on 2024-07-29 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondatamodel',
            name='id',
        ),
        migrations.AddField(
            model_name='jsondatamodel',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
