# Generated by Django 4.2.14 on 2024-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerymodel',
            name='district_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='state_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
