# Generated by Django 4.2.14 on 2024-08-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0002_summerymodel_district_name_summerymodel_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summerymodel',
            old_name='subdistrictCode',
            new_name='stateCode',
        ),
    ]
