# Generated by Django 4.2.14 on 2024-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0002_remove_jsondatamodel_id_jsondatamodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='districtCode',
            field=models.IntegerField(blank=True, default=-1, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='stateCode',
            field=models.IntegerField(blank=True, default=-1, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='subdistrictCode',
            field=models.IntegerField(blank=True, default=-1, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='villageCode',
            field=models.IntegerField(blank=True, default=-1, max_length=40, null=True),
        ),
    ]
