# Generated by Django 4.2.14 on 2024-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0003_datamodel_districtcode_datamodel_statecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='primaryType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
