# Generated by Django 4.2.14 on 2024-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0003_rename_subdistrictcode_summerymodel_statecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summerymodel',
            name='phase',
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='aggrigation_status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Pending'), (2, 'Started')], default=0),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='extraction_status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Pending'), (2, 'Started')], default=0),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='fetch_status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Pending'), (2, 'Started')], default=0),
        ),
    ]
