# Generated by Django 4.2.14 on 2024-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0004_remove_summerymodel_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerymodel',
            name='aggrigation_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Pending'), (3, 'Started')], default=0),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='extraction_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Pending'), (3, 'Started')], default=0),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='fetch_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Pending'), (3, 'Started')], default=0),
        ),
    ]
