# Generated by Django 4.2.14 on 2024-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0004_datamodel_primarytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catagory', models.CharField(blank=True, max_length=200, null=True)),
                ('subCatagory', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummeryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='districtCode',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='stateCode',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='subdistrictCode',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='villageCode',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
