# Generated by Django 4.2.14 on 2024-07-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0006_alter_datamodel_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='primaryType',
        ),
    ]
