# Generated by Django 4.2.14 on 2024-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0006_alter_summerymodel_aggrigation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerymodel',
            name='aggrigation_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Started', 'Started'), ('Failed', 'Failed')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='fetch_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Started', 'Started'), ('Failed', 'Failed')], default='Pending', max_length=200),
        ),
    ]
