# Generated by Django 4.2.14 on 2024-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0007_remove_datamodel_primarytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='catagory',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, to='strategicbi.catagorymodel'),
        ),
    ]
