# Generated by Django 4.2.14 on 2024-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0007_alter_summerymodel_aggrigation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerymodel',
            name='aggrigation_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='aggrigation_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='extraction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='extraction_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='fetch_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='fetch_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='aggrigation_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not started', 'Not started'), ('In-Progress', 'In-Progress'), ('Failed', 'Failed')], default='Not started', max_length=200),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='extraction_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not started', 'Not started'), ('In-Progress', 'In-Progress'), ('Failed', 'Failed')], default='Not started', max_length=200),
        ),
        migrations.AlterField(
            model_name='summerymodel',
            name='fetch_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not started', 'Not started'), ('In-Progress', 'In-Progress'), ('Failed', 'Failed')], default='Not started', max_length=200),
        ),
    ]
