# Generated by Django 4.2.14 on 2024-07-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0008_remove_datamodel_catagory_datamodel_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='catagory',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategicbi.catagorymodel'),
        ),
    ]
