# Generated by Django 4.2.14 on 2024-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0009_remove_summerymodel_aggrigation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerymodel',
            name='aggrigation_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='aggrigation_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='extraction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='extraction_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='fetch_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summerymodel',
            name='fetch_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
