# Generated by Django 4.2.14 on 2024-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0010_countmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countmodel',
            name='stateCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
