# Generated by Django 4.2.14 on 2024-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0012_alter_datamodel_locationlongitude_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countmodel',
            index=models.Index(fields=['stateCode', 'districtCode', 'catagory'], name='strategicbi_stateCo_6f885c_idx'),
        ),
    ]
