# Generated by Django 4.2.14 on 2024-08-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0013_countmodel_strategicbi_stateco_6f885c_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('lgd_access', 'lgd data access'), ('datamodel_access', 'extracted data access')]},
        ),
    ]
