# Generated by Django 4.2.14 on 2024-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicbi', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorymodel',
            name='catagory',
            field=models.CharField(blank=True, default='other', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
