# Generated by Django 5.0.7 on 2024-07-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stateCode', models.IntegerField(blank=True, null=True, unique=True)),
                ('stateNameEnglish', models.CharField(blank=True, max_length=300, null=True)),
                ('stateNameLocal', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('districtCode', models.IntegerField(blank=True, null=True, unique=True)),
                ('districtNameEnglish', models.CharField(blank=True, max_length=300, null=True)),
                ('districtNameLocal', models.CharField(blank=True, max_length=300, null=True)),
                ('stateCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.statemodel', to_field='stateCode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubDistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subDistrictCode', models.IntegerField(blank=True, null=True, unique=True)),
                ('subDistrictNameEnglish', models.CharField(blank=True, max_length=300, null=True)),
                ('subDistrictNameLocal', models.CharField(blank=True, max_length=300, null=True)),
                ('districtCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.districtmodel', to_field='districtCode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villageCode', models.IntegerField(blank=True, null=True, unique=True)),
                ('villageNameEnglish', models.CharField(blank=True, max_length=300, null=True)),
                ('villageNameLocal', models.CharField(blank=True, max_length=300, null=True)),
                ('subSidtrictCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.subdistrictmodel', to_field='subDistrictCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
