# Generated by Django 5.0.7 on 2024-07-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='stateCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.statemodel'),
        ),
        migrations.AlterField(
            model_name='subdistrictmodel',
            name='districtCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.districtmodel'),
        ),
        migrations.AlterField(
            model_name='villagemodel',
            name='subSidtrictCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.subdistrictmodel'),
        ),
        migrations.AlterField(
            model_name='villagemodel',
            name='villageCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
