# Generated by Django 5.0.7 on 2024-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0002_alter_districtmodel_statecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemodel',
            name='stateCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
