# Generated by Django 5.0.7 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0003_alter_statemodel_statecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='districtCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdistrictmodel',
            name='subDistrictCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
