# Generated by Django 4.2.14 on 2024-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('lgd access', 'lgd data access'), ('data model access', 'extracted data access')]},
        ),
    ]
