# Generated by Django 4.2.14 on 2024-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('lgd_access', 'lgd data access'), ('data_model_access', 'extracted data access')]},
        ),
    ]
